personal-portfolio-webpage
WALWALASAFI/personal-portfolio-webpage pull request #1
Opened 2024-06-06 11:54 UTC by WALWALASAFI

Personal-portflio-webpage ✔✨
this is a personal-portfolio-webpage. 💙
it is all information about myself and projects that I have done. 💙💙

2024-06-06 13:46 UTC, WALWALASAFI commented
@ahzamir

2024-06-06 19:05 UTC, WALWALASAFI commented
@ahzamir
sir this is my last portfolio webpage that I worked about one week on it, trust me , I worked so much on this project, to give an amazing  style and for this i have searched more and more, but unfortunately it got an error of lighthouse, that i will fix it as soon as possible. however i searched more, and asked from my partner and friends ,but  they don't know how to fix it. 😔😔

2024-06-06 19:34 UTC, ahzamir commented
@WALWALASAFI 

- Your HTML file does not have a name and also your pull request does not have a description after you solve these issues ask your partner for feedback.

2024-06-08 04:45 UTC, WALWALASAFI commented
@iamfarhatsharifi
darling check the project, as mentor said

2024-06-08 04:49 UTC, WALWALASAFI commented
@ahzamir sir i have finished, it was so easy just rename the html file and my the error is corrected. 
however, i searched in google more than 1 day it showed me a lot of requirement, like  install the NPM , other shows me got lighthouse link and download the lighthouse like that things, 
thanks a bunch sir

2024-06-08 12:10 UTC, ahzamir requested changes
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Well done walwala your portfolio looks amazing, although you have done a great job creating such an amazing portfolio and it passes all freecodecamp checks but your code is not clean.

- [OPTIONAL BUT REQUIRED FOR CAPSTONE PROJECT] - And if you want your portfolio to be counted as your capstone project, you need to add responsivness to your website and the source and live links of your projects.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Personal Portfolio and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your repo has a professional README.md file
❌Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-08 12:10 UTC, ahzamir commented on index.html
our HTML code is not clean and properly aligned. Please use 2 spaces for indentation instead of 4. Additionally, ensure that child elements are properly indented under their parent elements. Here's an example to help you:

**Incorrect:**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
        <h1>This is a Heading</h1>
        <p>This is a paragraph.</p>
    </body>
</html>
```

**Correct:**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>This is a Heading</h1>
    <p>This is a paragraph.</p>
  </body>
</html>
```

**Rule:** Each child element should be indented 2 spaces under its parent element for better readability and maintainability.
**Hint**: Go to the VSCode bottom right corner, you can see "Spaces: 4" (or a similar indicator). Click on that, then click on "Indent Using Spaces" and select 2. You can also use the gray color column lines to help you know where your parent and child elements should be.

2024-06-08 16:09 UTC, WALWALASAFI commented on index.html
hi sir,
i have done it

2024-06-08 16:43 UTC, WALWALASAFI commented on index.html
@ahzamir
Hi dear sir,
i have added 2 space

2024-07-20 04:48 UTC, merged